"""tables/watch and alert

Revision ID: ae59bdda9311
Revises: 
Create Date: 2026-05-20 14:19:32.191165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae59bdda9311'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('condition_type', sa.Enum('price_above', 'price_below', 'percent_change', 'market_cap_rank', name='conditiontype'), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watches_asset_is_active', 'watches', ['asset', 'is_active'], unique=False)
    op.create_index('ix_watches_user_id_is_active', 'watches', ['user_id', 'is_active'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watch_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('condition_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_watch_id', 'alerts', ['watch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_watch_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_watches_user_id_is_active', table_name='watches')
    op.drop_index('ix_watches_asset_is_active', table_name='watches')
    op.drop_table('watches')
    # ### end Alembic commands ###