#!/bin/bash
# Testing Guide for Billing Service Endpoints
# This script provides examples for testing all billing endpoints

echo "🧪 Billing Service Endpoint Testing Guide"
echo "=========================================="
echo ""
echo "Prerequisites:"
echo "1. Billing service running on http://localhost:8001"
echo "2. Valid Stripe test API key configured"
echo "3. JWT token with payload: {\"sub\": \"<uuid>\", \"email\": \"user@example.com\"}"
echo ""

# Example token (you need to generate a real JWT with your auth service)
# For testing, you can use: https://jwt.io to create a test token
# Payload:
# {
#   "sub": "550e8400-e29b-41d4-a716-446655440000",
#   "email": "test@example.com"
# }

TOKEN="YOUR_JWT_TOKEN_HERE"
BILLING_URL="http://localhost:8001"
USER_ID="550e8400-e29b-41d4-a716-446655440000"

echo ""
echo "⚙️  Setup - Generate a test JWT token"
echo "======================================"
echo "1. Go to https://jwt.io"
echo "2. Paste this payload in the 'Payload' section:"
echo '   {'
echo '     "sub": "550e8400-e29b-41d4-a716-446655440000",'
echo '     "email": "test@example.com"'
echo '   }'
echo "3. Copy the encoded token and replace TOKEN variable above"
echo ""

echo ""
echo "1️⃣  POST /billing/checkout - Create Checkout Session"
echo "====================================================="
echo "Description: Create Stripe Checkout Session for 'pro' plan upgrade"
echo ""
echo "curl -X POST $BILLING_URL/billing/checkout \\"
echo "  -H 'Authorization: Bearer $TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"plan\": \"pro\"}'"
echo ""
echo "✅ Success Response (200):"
echo "{"
echo "  \"checkout_url\": \"https://checkout.stripe.com/pay/cs_test_...\","
echo "  \"session_id\": \"cs_test_...\""
echo "}"
echo ""
echo "💳 Test this with:"
echo "   - Success card: 4242 4242 4242 4242"
echo "   - Auth required: 4000 0027 6000 3184"
echo "   - Declined card: 4000 0000 0000 0002"
echo ""
echo "For any card use expiry: 12/25 (or any future date)"
echo "CVC: 123 (any 3 digits)"
echo ""

echo ""
echo "2️⃣  POST /billing/portal - Create Customer Portal Session"
echo "=========================================================="
echo "Description: Get link to Stripe Customer Portal for self-service subscription management"
echo ""
echo "curl -X POST $BILLING_URL/billing/portal \\"
echo "  -H 'Authorization: Bearer $TOKEN' \\"
echo "  -H 'Content-Type: application/json'"
echo ""
echo "✅ Success Response (200):"
echo "{"
echo "  \"portal_url\": \"https://billing.stripe.com/\""
echo "}"
echo ""
echo "Features in Portal:"
echo "   - Update payment method"
echo "   - View invoices"
echo "   - Cancel subscription"
echo "   - Change subscription plan"
echo ""

echo ""
echo "3️⃣  GET /billing/subscriptions/me - Get Current Subscription"
echo "============================================================"
echo "Description: Retrieve current user's subscription status"
echo ""
echo "curl -X GET $BILLING_URL/billing/subscriptions/me \\"
echo "  -H 'Authorization: Bearer $TOKEN'"
echo ""
echo "✅ Success Response (200) - With Subscription:"
echo "{"
echo "  \"id\": \"550e8400-e29b-41d4-a716-446655440000\","
echo "  \"plan\": \"pro\","
echo "  \"status\": \"active\","
echo "  \"current_period_start\": \"2024-01-01T00:00:00Z\","
echo "  \"current_period_end\": \"2024-02-01T00:00:00Z\","
echo "  \"cancel_at_period_end\": false,"
echo "  \"created_at\": \"2024-01-01T00:00:00Z\""
echo "}"
echo ""
echo "✅ Success Response (200) - No Subscription (Free Plan):"
echo "{"
echo "  \"plan\": \"free\","
echo "  \"status\": \"active\","
echo "  \"current_period_end\": null,"
echo "  \"cancel_at_period_end\": false"
echo "}"
echo ""

echo ""
echo "4️⃣  POST /billing/cancel - Cancel Subscription at Period End"
echo "=============================================================="
echo "Description: Cancel user's subscription (access continues until period end)"
echo ""
echo "curl -X POST $BILLING_URL/billing/cancel \\"
echo "  -H 'Authorization: Bearer $TOKEN' \\"
echo "  -H 'Content-Type: application/json'"
echo ""
echo "✅ Success Response (200):"
echo "{"
echo "  \"status\": \"canceled\","
echo "  \"subscription_id\": \"sub_1234567890abcdef\","
echo "  \"cancel_at_period_end\": true"
echo "}"
echo ""
echo "❌ Error Response (400) - No active subscription:"
echo "{"
echo "  \"detail\": \"No active subscription found\""
echo "}"
echo ""

echo ""
echo "5️⃣  GET /billing/invoices - Get Invoice History"
echo "==============================================="
echo "Description: Get paginated list of user's invoices"
echo ""
echo "curl -X GET '$BILLING_URL/billing/invoices?limit=10&offset=0' \\"
echo "  -H 'Authorization: Bearer $TOKEN'"
echo ""
echo "✅ Success Response (200):"
echo "{"
echo "  \"invoices\": ["
echo "    {"
echo "      \"id\": \"in_1234567890abcdef\","
echo "      \"number\": \"INV-0001\","
echo "      \"amount_paid\": 9900,"
echo "      \"currency\": \"usd\","
echo "      \"status\": \"paid\","
echo "      \"created\": 1704067200,"
echo "      \"pdf_url\": \"https://invoices.stripe.com/...\""
echo "    }"
echo "  ],"
echo "  \"total\": 5,"
echo "  \"limit\": 10,"
echo "  \"offset\": 0"
echo "}"
echo ""

echo ""
echo "🔴 Error Handling Examples"
echo "=========================="
echo ""
echo "❌ 401 Unauthorized - Missing/Invalid Token:"
echo "curl -X GET $BILLING_URL/billing/subscriptions/me"
echo "Response: {\"detail\": \"Authentication required\"}"
echo ""
echo "❌ 400 Bad Request - Invalid Plan:"
echo "curl -X POST $BILLING_URL/billing/checkout \\"
echo "  -H 'Authorization: Bearer $TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"plan\": \"invalid_plan\"}'"
echo ""
echo "❌ 402 Payment Required - Card Declined:"
echo "Use declined test card: 4000 0000 0000 0002"
echo "Response: {\"detail\": \"Card declined. Please check your card details.\"}"
echo ""
echo "❌ 429 Too Many Requests - Rate Limited:"
echo "Response: {\"detail\": \"Too many requests\"}"
echo ""
echo "❌ 502 Bad Gateway - Stripe Error:"
echo "Response: {\"detail\": \"Payment processing error: ...\"}"
echo ""

echo ""
echo "🎯 Complete Test Flow"
echo "===================="
echo ""
echo "1. Get JWT token from auth service:"
echo "   curl -X POST http://localhost:8000/auth/login \\"
echo "     -d '{\"email\": \"test@example.com\", \"password\": \"password\"}' | jq '.token'"
echo ""
echo "2. Create checkout session:"
echo "   curl -X POST $BILLING_URL/billing/checkout \\"
echo "     -H \"Authorization: Bearer \$TOKEN\" \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"plan\": \"pro\"}'"
echo ""
echo "3. Open returned checkout_url in browser and complete payment"
echo ""
echo "4. Check subscription status:"
echo "   curl -X GET $BILLING_URL/billing/subscriptions/me \\"
echo "     -H \"Authorization: Bearer \$TOKEN\""
echo ""
echo "5. Open customer portal to manage subscription:"
echo "   curl -X POST $BILLING_URL/billing/portal \\"
echo "     -H \"Authorization: Bearer \$TOKEN\""
echo ""

echo ""
echo "🐛 Debugging Tips"
echo "================"
echo "1. Check service logs:"
echo "   docker logs coinwatch-billing"
echo ""
echo "2. Verify Stripe configuration:"
echo "   echo \$BILLING_STRIPE_SECRET_KEY"
echo ""
echo "3. Check database records:"
echo "   psql \$BILLING_DB_URL -c \"SELECT * FROM customers;\""
echo "   psql \$BILLING_DB_URL -c \"SELECT * FROM subscriptions;\""
echo ""
echo "4. Decode JWT token at https://jwt.io"
echo ""
echo "5. Check Stripe Dashboard (Test Mode):"
echo "   https://dashboard.stripe.com/test/dashboard"
echo ""

echo ""
echo "📚 Additional Resources"
echo "======================"
echo "- API Documentation: http://localhost:8001/docs"
echo "- ReDoc Documentation: http://localhost:8001/redoc"
echo "- OpenAPI Spec: http://localhost:8001/openapi.json"
echo "- Stripe Test Cards: https://stripe.com/docs/testing"
echo "- JWT.io: https://jwt.io"
echo ""
